"""'Init'

Revision ID: a29cdafbd92d
Revises: 
Create Date: 2022-11-29 17:51:11.154382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29cdafbd92d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('adresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress_name', sa.String(length=250), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_name', sa.String(length=100), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_name', sa.String(length=20), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_table('emails')
    op.drop_table('adresses')
    op.drop_table('records')
    # ### end Alembic commands ###
